import type { EmailItem, HandledGroup, ItemMeta, ActionConfig, ItemKind } from '@/types';

export const ITEMS: Record<string, EmailItem[]> = {
  review: [
    {
      id: 'vo-021',
      subj: 'Change order request: waterproofing variation VO-021',
      from: 'Sarah Chen · Halverson Iron',
      proj: 'NF-2118-CO-021',
      risk: 'Cost implication',
      action: 'Deferred',
      confidence: 91,
      age: '6h',
      body: `Per our scope walk yesterday, we're requesting a variation for the additional waterproofing membrane at the L2 podium slab perimeter — roughly 480 LF that wasn't in the issued-for-construction set. Our cost is $42,800 with a 4-day schedule impact. Please confirm by EOD Thursday so we can lock in the material order.`,
      why: `Email contains a dollar value over $25K and the phrase "variation request" — both trigger the cost-implication rule. Sender is the GC's commercial lead, recipient list includes the owner's rep. Auto-reply was suppressed.`,
      did: `Acknowledged receipt without commitment. Drafted a holding reply confirming we received the request and will respond within 48h after scope review. Tagged the procurement folder. No commercial language sent.`,
      next: `Review the variation scope against the IFC drawings and approve the holding reply, or reply directly if you've already made a decision.`,
      trail: [
        { t: 'Thu 14:32', e: 'Email received from Sarah Chen' },
        { t: 'Thu 14:32', e: 'Classified · cost-implication · 91% conf.' },
        { t: 'Thu 14:32', e: 'Rule triggered · safety_cost_claims_owner' },
        { t: 'Thu 14:33', e: 'Deferred · holding reply drafted' },
        { t: '—', e: 'Awaiting human review', pending: true },
      ],
    },
    {
      id: 'rfi-117',
      subj: 'RFI-117 reply draft — L4 conduit through shear wall',
      from: 'K. Ahmed · Site supervisor',
      proj: 'NF-2118-R05',
      risk: 'Routine · drafted',
      action: 'Reply drafted',
      confidence: 87,
      age: '1d',
      body: `Need direction on running the 4" EMT through the shear wall at gridline E/3. Drawing E-401 shows a sleeve, but the structural set doesn't pick it up. Two options sketched on the attached markup — Option A re-routes around, Option B uses a 6" cored sleeve.`,
      why: `Routine technical RFI from site. No commercial or safety flags. Drawing reference confirmed. Drafted but not sent because the response involves a design decision and I cap design decisions at human review.`,
      did: `Drafted a reply recommending Option B (cored sleeve) with a note for the EOR to confirm reinforcement detail. Pulled the relevant drawing references and attached.`,
      next: `Read the draft, send as-is or edit. If Option A is preferred, mark wrong call and I'll learn the preference for future RFIs at shear walls.`,
      trail: [
        { t: 'Wed 09:11', e: 'Email received from K. Ahmed' },
        { t: 'Wed 09:11', e: 'Classified · routine-rfi · 87% conf.' },
        { t: 'Wed 09:12', e: 'Drafted reply (Option B recommended)' },
        { t: '—', e: 'Awaiting human review', pending: true },
      ],
    },
    {
      id: 'sub-s44',
      subj: 'Stressing log bay 3 — release for review',
      from: 'Vermont Structural',
      proj: 'NF-2118-S44',
      risk: 'Routine · drafted',
      action: 'Reply drafted',
      confidence: 94,
      age: '1d',
      body: `Attached the stressing log for bay 3. All anchors within tolerance, two re-stressed per the QA plan.`,
      why: `Standard submittal package. All values inside tolerance band. Drafted approval reply but did not send — submittal approvals require a human signature per your rules.`,
      did: `Drafted "Reviewed — no exceptions" reply, filed under the submittals folder, and updated the submittals tracker.`,
      next: `Confirm the values look reasonable and approve, or open the log to review in detail.`,
      trail: [
        { t: 'Wed 16:04', e: 'Email received from Vermont Structural' },
        { t: 'Wed 16:04', e: 'Classified · submittal · 94% conf.' },
        { t: 'Wed 16:05', e: 'Drafted approval reply' },
        { t: '—', e: 'Awaiting human review', pending: true },
      ],
    },
    {
      id: 'sched-mep',
      subj: 'MEP rough-in — 2-day schedule slip detected',
      from: 'Cogram · auto-detect',
      proj: 'NF-2118',
      risk: 'Schedule risk',
      action: 'Flagged · no reply',
      confidence: 83,
      age: '2d',
      body: `Lift-pump delivery slipped from Tue to Thu. Two activities on the critical path now have zero float. Affected: MEP rough-in L4–L6.`,
      why: `Cross-referenced the vendor's delivery email with the live schedule. Critical-path impact crosses the schedule-risk threshold (2+ days). No auto-reply — schedule impacts go to you.`,
      did: `Drafted an internal note to the superintendent and the owner's rep. Nothing sent.`,
      next: `Decide whether to communicate the slip to the owner now or after the vendor confirms the new ETA.`,
      trail: [
        { t: 'Tue 11:48', e: 'Vendor email parsed · ETA shifted' },
        { t: 'Tue 11:49', e: 'Schedule cross-check · CP impact' },
        { t: 'Tue 11:49', e: 'Flagged · schedule-risk · 83% conf.' },
        { t: '—', e: 'Awaiting human review', pending: true },
      ],
    },
    {
      id: 'glaz-resub',
      subj: 'Curtain wall mockup — resubmittal #2',
      from: 'Apex Glazing',
      proj: 'NF-2118-S43',
      risk: 'Routine · drafted',
      action: 'Reply drafted',
      confidence: 79,
      age: '2d',
      body: `Resubmitted per your 7/14 comments. Sealant change to Dow 795 and revised anchor spacing.`,
      why: `Submittal resubmission. Drafted but not sent — submittals approvals need human signoff.`,
      did: `Verified the changes against your 7/14 markup. Drafted "Approved as noted" reply.`,
      next: `Confirm the markup items were addressed and approve.`,
      trail: [
        { t: 'Mon 10:22', e: 'Email received from Apex Glazing' },
        { t: 'Mon 10:23', e: 'Cross-checked vs prior markup' },
        { t: 'Mon 10:23', e: 'Drafted approval reply' },
        { t: '—', e: 'Awaiting human review', pending: true },
      ],
    },
  ],
  sensitive: [
    {
      id: 'claim-002',
      subj: 'Notice of claim — acceleration costs',
      from: 'McKenna & Co (counsel for GC)',
      proj: 'NF-2118-CL-002',
      risk: 'Claim · legal',
      action: 'Deferred · no reply',
      confidence: 97,
      age: '12h',
      body: `Formal notice of intent to claim acceleration costs of $187K relating to the Sept owner-directed re-sequencing. Please acknowledge receipt within 7 days per the contract.`,
      why: `Letter from counsel, "notice of intent to claim", dollar figure, contract clause cited. Five strong signals on the claims rule. Auto-reply blocked.`,
      did: `Nothing sent. Filed under claims folder, started a claim log entry, and added a calendar reminder for the 7-day acknowledgement window.`,
      next: `Loop in your commercial manager and project counsel before any response. I can draft a contract-compliant acknowledgement if you want.`,
      trail: [
        { t: 'Thu 02:14', e: 'Email received from McKenna & Co' },
        { t: 'Thu 02:14', e: 'Classified · claim · 97% conf.' },
        { t: 'Thu 02:14', e: 'Rule triggered · claims_legal' },
        { t: 'Thu 02:14', e: 'Auto-reply blocked' },
        { t: '—', e: 'Awaiting human review', pending: true },
      ],
    },
    {
      id: 'owner-esc',
      subj: 'Site walkthrough concerns — L7 finishes',
      from: "M. Ortega · Owner's rep",
      proj: 'NF-2118',
      risk: 'Owner escalation',
      action: 'Deferred · no reply',
      confidence: 88,
      age: '1d',
      body: `Walked L7 this morning. The drywall transitions at the lift lobby are not meeting the finish specification. This is the second time. Please advise how you intend to resolve before next week's owner meeting.`,
      why: `Owner-rep sender, "second time", reference to upcoming owner meeting. Owner-escalation rule triggered. No auto-reply.`,
      did: `Filed under owner-correspondence. Pulled the original spec and the prior remediation note. Nothing sent.`,
      next: `Reply personally. A draft is available if you'd like to start from one.`,
      trail: [
        { t: 'Wed 13:50', e: 'Email received from M. Ortega' },
        { t: 'Wed 13:50', e: 'Classified · owner-escalation · 88% conf.' },
        { t: 'Wed 13:51', e: 'Rule triggered · owner_escalation' },
        { t: '—', e: 'Awaiting human review', pending: true },
      ],
    },
    {
      id: 'safety-1',
      subj: 'Near miss · L3 scaffold tag missing',
      from: 'D. Park · Safety officer',
      proj: 'NF-2118',
      risk: 'Safety',
      action: 'Deferred · no reply',
      confidence: 96,
      age: '2d',
      body: `Daily safety walk found one section of scaffold on L3 with a missing inspection tag. No incident. Reissued the tag and re-inspected. Logging for the record.`,
      why: `Safety-officer sender plus "near miss" and "scaffold" in subject. Safety rule fired regardless of severity — I never auto-reply on safety.`,
      did: `Filed in the safety folder. Cross-linked to the scaffold inspection register. Nothing sent.`,
      next: `Acknowledge if you'd like. No further action otherwise.`,
      trail: [
        { t: 'Tue 16:20', e: 'Email received from D. Park' },
        { t: 'Tue 16:20', e: 'Classified · safety · 96% conf.' },
        { t: 'Tue 16:20', e: 'Rule triggered · safety' },
        { t: '—', e: 'Awaiting human review', pending: true },
      ],
    },
  ],
  lowconf: [
    {
      id: 'amb-1',
      subj: 'Quick question about the loading dock',
      from: 'unknown@gmail.com',
      proj: '—',
      risk: 'Ambiguous sender',
      action: 'Held · no reply',
      confidence: 42,
      age: '3d',
      body: `Hey — is the loading dock side accessible after 6pm? Want to drop something off.`,
      why: `Sender domain doesn't match any known vendor or contact. Subject is vague and lacks project reference. Confidence 42% — below my reply threshold.`,
      did: `Did not file, did not reply. Held in the review queue so you can decide whether to add the sender to the contact list or ignore.`,
      next: `Add to contacts or dismiss.`,
      trail: [
        { t: 'Mon 18:02', e: 'Email received from unknown@gmail.com' },
        { t: 'Mon 18:02', e: 'Classified · ambiguous · 42% conf.' },
        { t: 'Mon 18:02', e: 'Below auto-reply threshold' },
        { t: '—', e: 'Awaiting human review', pending: true },
      ],
    },
    {
      id: 'amb-2',
      subj: 'Re: revised drawings (no subject change since 06/14)',
      from: 'BIM Coordinator · BSA Design',
      proj: 'NF-2118',
      risk: 'Thread mismatch',
      action: 'Held · no reply',
      confidence: 58,
      age: '4d',
      body: `Latest from the architect. Note revision cloud on A-301 only.`,
      why: `Email is on a long-running thread whose subject no longer matches its current content. Confidence 58% — I'm not sure which prior thread this belongs to.`,
      did: `Held in the review queue. Did not file under a project folder to avoid mis-filing.`,
      next: `Tell me which thread this belongs to and I'll learn.`,
      trail: [
        { t: 'Mon 11:47', e: 'Email received from BSA Design' },
        { t: 'Mon 11:47', e: 'Thread match · 58% conf.' },
        { t: 'Mon 11:47', e: 'Held for review' },
        { t: '—', e: 'Awaiting human review', pending: true },
      ],
    },
    {
      id: 'amb-3',
      subj: 'Update?',
      from: 'jeff@acmecorp.io',
      proj: '—',
      risk: 'No context',
      action: 'Held · no reply',
      confidence: 31,
      age: '5d',
      body: `Any update on the thing we discussed?`,
      why: `No project reference, no thread history with this sender, no clear ask. Confidence 31% — well below threshold.`,
      did: `Held in the review queue. Did not respond.`,
      next: `Reply, dismiss, or block.`,
      trail: [
        { t: 'Sun 09:14', e: 'Email received from jeff@acmecorp.io' },
        { t: 'Sun 09:14', e: 'Classified · no-context · 31% conf.' },
        { t: '—', e: 'Awaiting human review', pending: true },
      ],
    },
  ],
};

export const HANDLED_GROUPS: HandledGroup[] = [
  { label: 'Routine RFIs filed', count: 14, note: 'Drawings cross-referenced, replies sent' },
  { label: 'Daily field reports archived', count: 11, note: 'Site logs L1–L9' },
  { label: 'Vendor quotes acknowledged', count: 9, note: 'No commercial commitment' },
  { label: 'Schedule pings replied', count: 7, note: 'Look-aheads, two-week pulls' },
  { label: 'Calendar invites accepted', count: 6, note: 'Coordination + OAC meetings' },
  { label: 'Newsletters dismissed', count: 5, note: 'Industry, vendor marketing' },
];

export const ITEM_META: Record<string, ItemMeta> = {
  'vo-021': {
    kind: 'sensitive',
    noReply: 'Cost-implication rule blocks any auto-reply on commercial commitments. Even an acknowledgement can be cited later in a dispute.',
  },
  'rfi-117': {
    kind: 'drafted',
    noReply: 'Design decisions need human signoff. I drafted a recommendation but did not send.',
  },
  'sub-s44': {
    kind: 'drafted',
    noReply: 'Submittal approvals require your signature per the project rules.',
  },
  'sched-mep': {
    kind: 'sensitive',
    noReply: 'Schedule slips that touch the critical path route to you. No notification was sent.',
  },
  'glaz-resub': {
    kind: 'drafted',
    noReply: 'Submittal approvals require your signature per the project rules.',
  },
  'claim-002': {
    kind: 'sensitive',
    noReply: 'Claims and legal correspondence are never auto-actioned. Any reply — even an acknowledgement — has contractual weight.',
  },
  'owner-esc': {
    kind: 'sensitive',
    noReply: 'Owner-rep escalations always route to you. They shape the project relationship.',
  },
  'safety-1': {
    kind: 'sensitive',
    noReply: 'I never auto-reply on safety, regardless of severity.',
  },
  'amb-1': {
    kind: 'held',
    noReply: "Confidence below my 70% reply threshold. I won't send something I'm not sure about.",
  },
  'amb-2': {
    kind: 'held',
    noReply: 'Confidence below my 70% reply threshold.',
  },
  'amb-3': {
    kind: 'held',
    noReply: 'Confidence below my 70% reply threshold.',
  },
};

export const ACTIONS_BY_KIND: Record<ItemKind, ActionConfig> = {
  sensitive: { primary: 'Send holding reply', secondary: ['Edit', 'Defer'] },
  drafted: { primary: 'Approve draft reply', secondary: ['Edit', 'Defer'] },
  held: { primary: 'Reply manually', secondary: ['Dismiss', 'Defer'] },
};
